# Generated by Django 3.2 on 2023-06-28 01:31

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'hr_tool/fixtures/initial_master.json', app_label='hr_tool')
    call_command('loaddata', 'hr_tool/fixtures/initial_transaction.json', app_label='hr_tool')


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
