# Generated by Django 3.2 on 2023-06-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0002_auto_20230628_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttrainingexp',
            old_name='training_id',
            new_name='training',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='homeoffice_id',
            new_name='homeoffice',
        ),
    ]
