# Generated by Django 3.2 on 2023-06-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0003_auto_20230630_1006'),
        ('hr_tool', '0004_auto_20230629_1744'),
    ]

    operations = [
    ]
